"""add_tags_fix_auth

Revision ID: 20703fa1b7c3
Revises: e3a51bf2a214
Create Date: 2025-09-26 07:44:39.189414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20703fa1b7c3'
down_revision: Union[str, Sequence[str], None] = 'e3a51bf2a214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_tags', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint('_product_tag_uc', 'product_tags', ['product_id', 'tag_id'])
    op.create_index(op.f('ix_product_tags_id'), 'product_tags', ['id'], unique=False)
    op.add_column('tags', sa.Column('value', sa.String(), nullable=True))
    op.create_index(op.f('ix_tags_value'), 'tags', ['value'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_value'), table_name='tags')
    op.drop_column('tags', 'value')
    op.drop_index(op.f('ix_product_tags_id'), table_name='product_tags')
    op.drop_constraint('_product_tag_uc', 'product_tags', type_='unique')
    op.drop_column('product_tags', 'id')
    # ### end Alembic commands ###
