"""filters

Revision ID: 20764c64b897
Revises: bad033cca5f0
Create Date: 2025-09-25 04:50:16.258247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20764c64b897'
down_revision: Union[str, Sequence[str], None] = 'bad033cca5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_items_id'), 'filter_items', ['id'], unique=False)
    op.create_table('characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('filter_id', sa.Integer(), nullable=True),
    sa.Column('filter_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ),
    sa.ForeignKeyConstraint(['filter_item_id'], ['filter_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characteristics_id'), 'characteristics', ['id'], unique=False)
    op.add_column('filters', sa.Column('value', sa.String(), nullable=True))
    op.create_index(op.f('ix_filters_value'), 'filters', ['value'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filters_value'), table_name='filters')
    op.drop_column('filters', 'value')
    op.drop_index(op.f('ix_characteristics_id'), table_name='characteristics')
    op.drop_table('characteristics')
    op.drop_index(op.f('ix_filter_items_id'), table_name='filter_items')
    op.drop_table('filter_items')
    # ### end Alembic commands ###
