"""make_slug_optional_fix_models

Revision ID: 67d8e7eedf0b
Revises: 67ea59e93ebe
Create Date: 2025-09-21 01:59:18.518160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d8e7eedf0b'
down_revision: Union[str, Sequence[str], None] = '67ea59e93ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
