"""fix characteristics

Revision ID: ae9ceb5e855f
Revises: fd15800909d0
Create Date: 2025-09-29 02:30:02.848776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9ceb5e855f'
down_revision: Union[str, Sequence[str], None] = 'fd15800909d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristics', sa.Column('slug', sa.String(length=100), nullable=True))
    op.add_column('characteristics', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('characteristics', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('characteristics', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('characteristics', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('characteristics', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_characteristics_name'), table_name='characteristics')
    op.drop_index(op.f('ix_characteristics_value'), table_name='characteristics')
    op.create_index(op.f('ix_characteristics_slug'), 'characteristics', ['slug'], unique=True)
    op.drop_constraint(op.f('characteristics_product_id_fkey'), 'characteristics', type_='foreignkey')
    op.drop_constraint(op.f('characteristics_template_id_fkey'), 'characteristics', type_='foreignkey')
    op.drop_column('characteristics', 'template_id')
    op.drop_column('characteristics', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristics', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characteristics', sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('characteristics_template_id_fkey'), 'characteristics', 'characteristic_templates', ['template_id'], ['id'])
    op.create_foreign_key(op.f('characteristics_product_id_fkey'), 'characteristics', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_characteristics_slug'), table_name='characteristics')
    op.create_index(op.f('ix_characteristics_value'), 'characteristics', ['value'], unique=False)
    op.create_index(op.f('ix_characteristics_name'), 'characteristics', ['name'], unique=False)
    op.alter_column('characteristics', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('characteristics', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('characteristics', 'updated_at')
    op.drop_column('characteristics', 'created_at')
    op.drop_column('characteristics', 'is_active')
    op.drop_column('characteristics', 'slug')
    # ### end Alembic commands ###
