"""fix

Revision ID: bad033cca5f0
Revises: ae1c0148f9dc
Create Date: 2025-09-25 03:43:28.169379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad033cca5f0'
down_revision: Union[str, Sequence[str], None] = 'ae1c0148f9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characteristic_templates_id'), table_name='characteristic_templates')
    op.drop_index(op.f('ix_characteristic_templates_name'), table_name='characteristic_templates')
    op.drop_table('characteristic_templates')
    op.drop_index(op.f('ix_product_characteristics_id'), table_name='product_characteristics')
    op.drop_table('product_characteristics')
    op.drop_index(op.f('ix_characteristics_id'), table_name='characteristics')
    op.drop_index(op.f('ix_characteristics_name'), table_name='characteristics')
    op.drop_table('characteristics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristics',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('characteristics_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='characteristics_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_characteristics_name'), 'characteristics', ['name'], unique=True)
    op.create_index(op.f('ix_characteristics_id'), 'characteristics', ['id'], unique=False)
    op.create_table('product_characteristics',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('characteristic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristics.id'], name=op.f('product_characteristics_characteristic_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_characteristics_product_id_fkey'))
    )
    op.create_index(op.f('ix_product_characteristics_id'), 'product_characteristics', ['id'], unique=False)
    op.create_table('characteristic_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('characteristic_templates_pkey'))
    )
    op.create_index(op.f('ix_characteristic_templates_name'), 'characteristic_templates', ['name'], unique=False)
    op.create_index(op.f('ix_characteristic_templates_id'), 'characteristic_templates', ['id'], unique=False)
    # ### end Alembic commands ###
