"""brands and products fix v2

Revision ID: c008bf3c48ef
Revises: b54239540061
Create Date: 2025-09-30 09:46:37.127987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c008bf3c48ef'
down_revision: Union[str, Sequence[str], None] = 'b54239540061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('characteristics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'characteristics')
    # ### end Alembic commands ###
