"""add product characteristics

Revision ID: ef50f692fa87
Revises: d1e0812d5b73
Create Date: 2025-09-25 03:06:03.249888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef50f692fa87'
down_revision: Union[str, Sequence[str], None] = 'd1e0812d5b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characteristics_name'), table_name='characteristics')
    op.create_index(op.f('ix_characteristics_name'), 'characteristics', ['name'], unique=True)
    op.drop_constraint(op.f('characteristics_template_id_fkey'), 'characteristics', type_='foreignkey')
    op.drop_column('characteristics', 'value')
    op.drop_column('characteristics', 'template_id')
    op.add_column('product_characteristics', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('product_characteristics', sa.Column('value', sa.String(), nullable=True))
    op.create_index(op.f('ix_product_characteristics_id'), 'product_characteristics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_characteristics_id'), table_name='product_characteristics')
    op.drop_column('product_characteristics', 'value')
    op.drop_column('product_characteristics', 'id')
    op.add_column('characteristics', sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characteristics', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('characteristics_template_id_fkey'), 'characteristics', 'characteristic_templates', ['template_id'], ['id'])
    op.drop_index(op.f('ix_characteristics_name'), table_name='characteristics')
    op.create_index(op.f('ix_characteristics_name'), 'characteristics', ['name'], unique=False)
    # ### end Alembic commands ###
