"""Add filters and filter_items tables

Revision ID: fd15800909d0
Revises: c0d266634a45
Create Date: 2025-09-29 00:11:20.879789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd15800909d0'
down_revision: Union[str, Sequence[str], None] = 'c0d266634a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristics', sa.Column('name', sa.String(), nullable=True))
    op.add_column('characteristics', sa.Column('value', sa.String(), nullable=True))
    op.add_column('characteristics', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('characteristics', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_characteristics_name'), 'characteristics', ['name'], unique=False)
    op.create_index(op.f('ix_characteristics_value'), 'characteristics', ['value'], unique=False)
    op.drop_constraint(op.f('characteristics_filter_item_id_fkey'), 'characteristics', type_='foreignkey')
    op.drop_constraint(op.f('characteristics_filter_id_fkey'), 'characteristics', type_='foreignkey')
    op.create_foreign_key(None, 'characteristics', 'characteristic_templates', ['template_id'], ['id'])
    op.drop_column('characteristics', 'filter_item_id')
    op.drop_column('characteristics', 'filter_id')
    op.add_column('filter_items', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('filter_items', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('filter_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('filter_items', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('filter_items', 'label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('filters', sa.Column('label', sa.String(length=255), nullable=False))
    op.add_column('filters', sa.Column('slug', sa.String(length=100), nullable=True))
    op.add_column('filters', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('filters', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('filters', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('filters', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('filters', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_filters_text'), table_name='filters')
    op.create_index(op.f('ix_filters_slug'), 'filters', ['slug'], unique=True)
    op.drop_constraint(op.f('filters_category_id_fkey'), 'filters', type_='foreignkey')
    op.drop_column('filters', 'category_id')
    op.drop_column('filters', 'text')
    op.drop_column('filters', 'status')
    op.drop_column('filters', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filters', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('filters', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('filters', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('filters', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('filters_category_id_fkey'), 'filters', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_filters_slug'), table_name='filters')
    op.create_index(op.f('ix_filters_text'), 'filters', ['text'], unique=False)
    op.alter_column('filters', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('filters', 'updated_at')
    op.drop_column('filters', 'created_at')
    op.drop_column('filters', 'is_active')
    op.drop_column('filters', 'order_index')
    op.drop_column('filters', 'slug')
    op.drop_column('filters', 'label')
    op.alter_column('filter_items', 'label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('filter_items', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('filter_items', 'created_at')
    op.drop_column('filter_items', 'is_active')
    op.drop_column('filter_items', 'order_index')
    op.add_column('characteristics', sa.Column('filter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characteristics', sa.Column('filter_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'characteristics', type_='foreignkey')
    op.create_foreign_key(op.f('characteristics_filter_id_fkey'), 'characteristics', 'filters', ['filter_id'], ['id'])
    op.create_foreign_key(op.f('characteristics_filter_item_id_fkey'), 'characteristics', 'filter_items', ['filter_item_id'], ['id'])
    op.drop_index(op.f('ix_characteristics_value'), table_name='characteristics')
    op.drop_index(op.f('ix_characteristics_name'), table_name='characteristics')
    op.drop_column('characteristics', 'template_id')
    op.drop_column('characteristics', 'order_index')
    op.drop_column('characteristics', 'value')
    op.drop_column('characteristics', 'name')
    # ### end Alembic commands ###
